title: Vehiclepedia
theme: docdock
baseURL: https://vehiclepedia.united-drivers.org/
languageCode: en-us
DefaultContentLanguage: "en"
author:
  name: United Drivers
  email: contact@united-drivers.org
  #logo

#pygmentsCodeFences = true
#pygmentsStyle = "monokailight"
defaultContentLanguageInSubdir: false
enableMissingTranslationPlaceholders: false

editURL: "https://github.com/united-drivers/vehiclepedia/edit/master/content/"
showVisitedLinks: true # default is false
themeStyle: "flex" # "original" or "flex" # default "flex"
themeVariant: "gold" # choose theme variant "green", "gold" , "gray", "blue" (default)
#ordersectionsby: "weight" # ordersectionsby = "title" or "weight"
ordersectionsby: title
disableHomeIcon: false # default is false
disableSearch: false # default is false
disableNavChevron: false # set true to hide next/prev chevron, default is false
highlightClientSide: false # set true to use highlight.pack.js instead of the default hugo chroma highlighter
menushortcutsnewtab: false # set true to open shortcuts links to a new tab/window
enableGitInfo: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

menu:
  shortcuts:
    - pre: "<h3>More</h3>"
      name: "<i class='fa fa-github'></i> <label>Github repo</label>"
      identifier: "ds"
      url: "https://github.com/united-drivers/vehiclepedia"
      weight: 10

    - name: "<i class='fa fa-cloud-download'></i> <label>Download</label>"
      url: "https://github.com/united-drivers/vehiclepedia/archive/master.zip"
      weight: 11

    - name: "<i class='fa fa-bookmark'></i> <label>United Drivers</label>"
      identifier: "uniteddrivers"
      url: "https://www.united-drivers.org/"
      weight: 20

    - name: "<i class='fa fa-bookmark'></i> <label>Wulo</label>"
      identifier: "wulo"
      url: "https://www.wulo.fr/"
      weight: 20

    - name: "<i class='fa fa-bullhorn'></i> <label>Credits</label>"
      url: "/credits"
      weight: 30


params:
  googleAnalytics: "UA-91920345-3"
#  description: "An open-source, free and collaborative vehicles database"
#  copyright: Unlicense.org
#  title: Vehiclepedia
#  subtitle: "An open-source, free and collaborative vehicles database"
  useSummaryIfNoDescription: true
