version: 2
jobs:
  build:
    docker:
      - image: starefossen/ruby-node
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback
            - v2-dependencies-
      - run: make deps
      - save_cache:
          paths:
            - "/usr/local/bundle"
            - "/usr/local/lib/node_modules"
          key: v2-dependencies-{{ checksum "Gemfile.lock" }}
      - run: make build
      - run: make test
      # deploy
